title: Casper Eide Özdemir-Børretzen
url: https://laser-wolf.github.io
bash_user: laser_wolf@arch

permalink: pretty
baseurl: ""

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    default_lang: csharp
#    block:
#      line_numbers: true

toc:
  ordered_list: true

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-analytics
  - jekyll-feed
  - jekyll-toc

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-C555550WZD        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
