# The main config file for your Jekyll template

# Site settings
#title: Casper Børretzen
#desc: ...

url: https://laser-wolf.github.io    # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: casper.eide@gmail.com
#author: Casper Børretzen
twitter_username: LASER_WOLF
github_username: LASER-WOLF
github_source: laser-wolf.github.io

# Put your ga tracking code below
#google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/posts/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Posts
    url: /posts/
    desc: Posts
  - title: About
    url: /about/
    desc: About me

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

